import { z } from 'zod';

import { AssistantConversationStatus, AssistantCursorScope, AssistantErrorCode, AssistantHandoffReason, AssistantInboxEventType, AssistantStreamEventType } from '../../domain/assistant/assistant.enums';
import { SUPPORTED_LOCALES } from '../../domain/common/common.constants';
export const ASSISTANT_MESSAGE_MAX_LENGTH = 8000;
export const ASSISTANT_TITLE_MAX_LENGTH = 160;
export const ASSISTANT_LIST_LIMIT_MAX = 100;
export const ASSISTANT_HISTORY_LIMIT_MAX = 100;
const uuid = z.uuid();
const sequence = z.string().regex(/^\d+$/);
export const createAssistantConversationSchema = z.object({ locale: z.enum(SUPPORTED_LOCALES), clientConversationId: uuid }).strict();
export const updateAssistantConversationSchema = z.object({ title: z.string().trim().min(1).max(ASSISTANT_TITLE_MAX_LENGTH) }).strict();
export const markAssistantConversationReadSchema = z.object({ throughSequence: sequence }).strict();
export const requestSupportSchema = z.object({ reason: z.enum(AssistantHandoffReason), sourceMessageId: uuid.optional() }).strict();
export const createAssistantMessageSchema = z.object({ clientMessageId: uuid, content: z.string().trim().min(1).max(ASSISTANT_MESSAGE_MAX_LENGTH) }).strict();
export const streamAssistantMessageSchema = createAssistantMessageSchema;
export const retryAssistantMessageSchema = z.object({ clientAttemptId: uuid }).strict();
export const assistantConversationListQuerySchema = z.object({ cursor: z.string().max(2048).optional(), limit: z.coerce.number().int().min(1).max(ASSISTANT_LIST_LIMIT_MAX).default(20), status: z.enum(AssistantConversationStatus).optional() }).strict();
export const assistantMessageListQuerySchema = z.object({ beforeSequence: sequence.optional(), limit: z.coerce.number().int().min(1).max(ASSISTANT_HISTORY_LIMIT_MAX).default(50) }).strict();
export const assistantEventsQuerySchema = z.object({ after: z.string().max(2048).optional() }).strict();
export const assistantSignedCursorSchema = z.object({ v: z.literal(1), sub: uuid, after: sequence, iat: z.number().int().nonnegative(), exp: z.number().int().positive(), scope: z.enum(AssistantCursorScope) }).strict();
export const assistantErrorSchema = z.object({ code: z.enum(AssistantErrorCode), retryable: z.boolean(), messageKey: z.string().min(1).max(160), requestId: z.string().min(1).max(128) }).strict();
export const assistantStreamEventEnvelopeSchema = z.object({ eventType: z.enum(AssistantStreamEventType) }).passthrough();
export const assistantInboxEventEnvelopeSchema = z.object({ eventType: z.enum(AssistantInboxEventType) }).passthrough();
