import { createHash, randomUUID } from 'crypto';

import { Injectable } from '@nestjs/common';
import type { PoolClient } from 'pg';

import { DatabaseService } from '../../common/database/database.service';

import { EmbeddingService, type EmbeddingSpace } from './embedding.service';
import { KNOWLEDGE_EMBED_BATCH_SIZE, KNOWLEDGE_EXPECTED_PAIR_COUNT, PersistedKnowledgeReleaseStatus, PersistedKnowledgeVersionStatus } from './knowledge-ingestion.constants';
import { chunkKnowledge, loadKnowledgeManifest, type KnowledgeManifest, type KnowledgeManifestItem } from './knowledge-manifest';

export interface KnowledgeValidationResult { manifest: KnowledgeManifest; manifestChecksum: string; pairCount: number; chunkCount: number; files: Map<string,string> }
export interface KnowledgeIngestionResult { releaseId: string; manifestChecksum: string; itemCount: number; chunkCount: number; reused: boolean }
export interface KnowledgeReleaseStatusResult { activeReleaseId: string|null; releases: Array<{id:string;status:PersistedKnowledgeReleaseStatus;manifestChecksum:string;itemCount:number;embeddingSpaceId:string|null;createdAt:Date}> }

type Frontmatter={title:string;summary:string};
type SpaceRow={id:string};
type ReleaseRow={id:string;status:PersistedKnowledgeReleaseStatus};
type VersionRow={id:string};
const sha=(value:string):string=>createHash('sha256').update(value).digest('hex');

@Injectable()
export class KnowledgeIngestionService {
 constructor(private readonly database:DatabaseService,private readonly embeddings:EmbeddingService){}
 async validate(root:string):Promise<KnowledgeValidationResult>{
  const loaded=await loadKnowledgeManifest(root); const slugs=new Set(loaded.manifest.items.map(item=>item.slug));
  if(slugs.size!==KNOWLEDGE_EXPECTED_PAIR_COUNT){throw new Error('manifest_invalid');}
  let chunkCount=0; for(const item of loaded.manifest.items){const text=loaded.files.get(item.sourcePath); if(!text){throw new Error('manifest_invalid');} this.frontmatter(text); const chunks=chunkKnowledge(text); if(!chunks.length){throw new Error('frontmatter_invalid');} chunkCount+=chunks.length;}
  return {...loaded,manifestChecksum:sha(JSON.stringify([...loaded.manifest.items].sort((a,b)=>a.sourcePath.localeCompare(b.sourcePath)))),pairCount:slugs.size,chunkCount};
 }
 async dryRun(root:string):Promise<Omit<KnowledgeValidationResult,'files'|'manifest'>>{const value=await this.validate(root);return {manifestChecksum:value.manifestChecksum,pairCount:value.pairCount,chunkCount:value.chunkCount};}
 async ingest(root:string):Promise<KnowledgeIngestionResult>{
  const candidate=await this.validate(root); const existing=await this.database.query<ReleaseRow>('SELECT id,status FROM knowledge_corpus_releases WHERE manifest_checksum=$1',[candidate.manifestChecksum]);
  if(existing[0]&&existing[0].status!==PersistedKnowledgeReleaseStatus.FAILED){return {releaseId:existing[0].id,manifestChecksum:candidate.manifestChecksum,itemCount:candidate.pairCount,chunkCount:candidate.chunkCount,reused:true};}
  const space=this.embeddings.space(); const vectors=new Map<string,number[]>();
  try {const entries=candidate.manifest.items.flatMap(item=>chunkKnowledge(candidate.files.get(item.sourcePath) as string).map(chunk=>({key:`${item.sourcePath}:${chunk.ordinal}`,content:chunk.content}))); for(let offset=0;offset<entries.length;offset+=KNOWLEDGE_EMBED_BATCH_SIZE){const batch=entries.slice(offset,offset+KNOWLEDGE_EMBED_BATCH_SIZE);const embedded=await this.embeddings.embed(batch.map(x=>x.content));batch.forEach((entry,index)=>vectors.set(entry.key,embedded[index]));}
   return await this.database.transaction(client=>this.persistCandidate(client,candidate,space,vectors));
  } catch(error){await this.markFailed(candidate.manifestChecksum);throw new Error(this.safeDiagnostic(error));}
 }
 async publish(releaseId:string):Promise<void>{await this.database.transaction(async client=>{await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',['knowledge-active-release']);const ready=await client.query<{count:number;expected:number}>('SELECT COUNT(DISTINCT i.document_id)::int count,r.item_count::int expected FROM knowledge_corpus_releases r LEFT JOIN knowledge_corpus_release_items i ON i.release_id=r.id WHERE r.id=$1 AND r.status=$2 GROUP BY r.item_count',[releaseId,PersistedKnowledgeReleaseStatus.BUILDING]);if(!ready.rows[0]||ready.rows[0].count!==ready.rows[0].expected){throw new Error('release_incomplete');}const active=await client.query<{release_id:string}>('SELECT release_id FROM knowledge_active_release WHERE singleton=TRUE FOR UPDATE');await client.query('UPDATE knowledge_corpus_releases SET status=$2,published_at=NOW() WHERE id=$1',[releaseId,PersistedKnowledgeReleaseStatus.PUBLISHED]);await client.query('INSERT INTO knowledge_active_release(singleton,release_id,activated_at) VALUES(TRUE,$1,NOW()) ON CONFLICT(singleton) DO UPDATE SET release_id=EXCLUDED.release_id,activated_at=EXCLUDED.activated_at',[releaseId]);if(active.rows[0]&&active.rows[0].release_id!==releaseId){await client.query('UPDATE knowledge_corpus_releases SET status=$2,retired_at=NOW() WHERE id=$1',[active.rows[0].release_id,PersistedKnowledgeReleaseStatus.RETIRED]);}});}
 async rollback(releaseId:string):Promise<void>{await this.database.transaction(async client=>{await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',['knowledge-active-release']);const target=await client.query<{id:string}>('SELECT id FROM knowledge_corpus_releases WHERE id=$1 AND status IN ($2,$3) FOR UPDATE',[releaseId,PersistedKnowledgeReleaseStatus.PUBLISHED,PersistedKnowledgeReleaseStatus.RETIRED]);if(!target.rows[0]){throw new Error('release_not_found');}const active=await client.query<{release_id:string}>('SELECT release_id FROM knowledge_active_release WHERE singleton=TRUE FOR UPDATE');await client.query('INSERT INTO knowledge_active_release(singleton,release_id,activated_at) VALUES(TRUE,$1,NOW()) ON CONFLICT(singleton) DO UPDATE SET release_id=EXCLUDED.release_id,activated_at=EXCLUDED.activated_at',[releaseId]);if(active.rows[0]&&active.rows[0].release_id!==releaseId){await client.query('UPDATE knowledge_corpus_releases SET status=$2,retired_at=NOW() WHERE id=$1',[active.rows[0].release_id,PersistedKnowledgeReleaseStatus.RETIRED]);}});}
 async status():Promise<KnowledgeReleaseStatusResult>{const active=await this.database.query<{release_id:string}>('SELECT release_id FROM knowledge_active_release WHERE singleton=TRUE');const rows=await this.database.query<{id:string;status:PersistedKnowledgeReleaseStatus;manifest_checksum:string;item_count:number;embedding_space_id:string|null;created_at:Date}>('SELECT id,status,manifest_checksum,item_count,embedding_space_id,created_at FROM knowledge_corpus_releases ORDER BY created_at DESC');return {activeReleaseId:active[0]?.release_id??null,releases:rows.map(r=>({id:r.id,status:r.status,manifestChecksum:r.manifest_checksum,itemCount:r.item_count,embeddingSpaceId:r.embedding_space_id,createdAt:r.created_at}))};}
 private async persistCandidate(client:PoolClient,c:KnowledgeValidationResult,space:EmbeddingSpace,vectors:Map<string,number[]>):Promise<KnowledgeIngestionResult>{const table=space.dimensions===768?'knowledge_embeddings_768':'knowledge_embeddings_1536';const sr=await client.query<SpaceRow>('INSERT INTO knowledge_embedding_spaces(provider,model,dimensions,distance_metric,physical_table) VALUES($1,$2,$3,$4,$5) ON CONFLICT(provider,model,dimensions,distance_metric) DO UPDATE SET model=EXCLUDED.model RETURNING id',[space.provider,space.model,space.dimensions,space.distanceMetric,table]);const releaseId=randomUUID();await client.query('INSERT INTO knowledge_corpus_releases(id,release_key,status,manifest_checksum,embedding_space_id,item_count) VALUES($1,$2,$3,$4,$5,$6)',[releaseId,randomUUID(),PersistedKnowledgeReleaseStatus.BUILDING,c.manifestChecksum,sr.rows[0].id,c.pairCount]);const pairs=this.pairs(c.manifest.items);for(const [slug,pair] of pairs){const doc=await client.query<{id:string}>('INSERT INTO knowledge_documents(slug,visibility) VALUES($1,$2) ON CONFLICT(slug) DO UPDATE SET updated_at=NOW() RETURNING id',[slug,'customer']);const ids=new Map<string,string>();for(const item of [pair.en,pair.tr]){const text=c.files.get(item.sourcePath) as string;const fm=this.frontmatter(text);const vr=await client.query<VersionRow>('INSERT INTO knowledge_document_versions(document_id,locale,version,title,summary,source_path,source_checksum,content_checksum,status,published_at,ingested_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW(),NOW()) ON CONFLICT(document_id,locale,version) DO UPDATE SET status=EXCLUDED.status RETURNING id',[doc.rows[0].id,item.locale,item.version,fm.title,fm.summary,item.sourcePath,item.checksum,sha(text),PersistedKnowledgeVersionStatus.PUBLISHED]);ids.set(item.locale,vr.rows[0].id);for(const chunk of chunkKnowledge(text)){const cr=await client.query<{id:string}>('INSERT INTO knowledge_chunks(document_version_id,ordinal,heading_path,content,token_count,content_hash) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(document_version_id,ordinal) DO UPDATE SET content=EXCLUDED.content RETURNING id',[vr.rows[0].id,chunk.ordinal,chunk.headingPath,chunk.content,chunk.tokenCount,chunk.contentHash]);const vector=vectors.get(`${item.sourcePath}:${chunk.ordinal}`);if(!vector){throw new Error('release_incomplete');}await client.query(`INSERT INTO ${table}(chunk_id,release_id,space_id,embedding) VALUES($1,$2,$3,$4::vector)`,[cr.rows[0].id,releaseId,sr.rows[0].id,`[${vector.join(',')}]`]);}}await client.query('INSERT INTO knowledge_corpus_release_items(release_id,document_id,en_version_id,tr_version_id,pair_checksum) VALUES($1,$2,$3,$4,$5)',[releaseId,doc.rows[0].id,ids.get('en'),ids.get('tr'),sha(pair.en.checksum+pair.tr.checksum)]);}return {releaseId,manifestChecksum:c.manifestChecksum,itemCount:c.pairCount,chunkCount:c.chunkCount,reused:false};}
 private pairs(items:KnowledgeManifestItem[]):Map<string,{en:KnowledgeManifestItem;tr:KnowledgeManifestItem}>{const out=new Map<string,{en?:KnowledgeManifestItem;tr?:KnowledgeManifestItem}>();for(const item of items){const pair=out.get(item.slug)??{};pair[item.locale]=item;out.set(item.slug,pair);}return new Map([...out].map(([slug,p])=>{if(!p.en||!p.tr){throw new Error('locale_pair_missing');}return [slug,{en:p.en,tr:p.tr}];}));}
 private frontmatter(text:string):Frontmatter{const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(text);const title=/^title:\s*(.+)$/m.exec(match?.[1]??'')?.[1]?.trim();const summary=/^summary:\s*(.+)$/m.exec(match?.[1]??'')?.[1]?.trim();if(!title||!summary){throw new Error('frontmatter_invalid');}return {title,summary};}
 private async markFailed(checksum:string):Promise<void>{try{await this.database.query('UPDATE knowledge_corpus_releases SET status=$2 WHERE manifest_checksum=$1 AND status=$3',[checksum,PersistedKnowledgeReleaseStatus.FAILED,PersistedKnowledgeReleaseStatus.BUILDING]);}catch{return;}}
 private safeDiagnostic(error:unknown):string{const message=error instanceof Error?error.message:'ingestion_failed';return /^[a-z_]+$/.test(message)?message:'ingestion_failed';}
}
