export enum KnowledgeDocumentCategory { ONBOARDING = 'onboarding', EBAY = 'ebay', AMAZON_ACCOUNTS = 'amazon_accounts', LISTINGS = 'listings', DRAFTS = 'drafts', LISTING_GROUPS = 'listing_groups', REPRICING_QUANTITY = 'repricing_quantity', ORDERS_LINKING = 'orders_linking', PROFIT = 'profit', AUTO_COST_CAPTURE = 'auto_cost_capture', AUTO_FULFILL = 'auto_fulfill', TRACKING = 'tracking', STORE_SETTINGS = 'store_settings', GOOGLE_AUTH = 'google_auth', CONTENT_AI = 'content_ai', ASSISTANT_SUPPORT = 'assistant_support', TROUBLESHOOTING = 'troubleshooting', PRIVACY = 'privacy' }
export enum KnowledgeVisibility { CUSTOMER = 'customer' }
export enum KnowledgeFrontmatterStatus { PUBLISHED = 'published', ARCHIVED = 'archived' }
export enum KnowledgeIngestionSource { CURATED_REPOSITORY = 'curated_repository' }
export enum KnowledgeIngestionStatus { PENDING = 'pending', VALIDATING = 'validating', CHUNKING = 'chunking', EMBEDDING = 'embedding', READY_TO_PUBLISH = 'ready_to_publish', PUBLISHED = 'published', FAILED = 'failed', CANCELLED = 'cancelled' }
export enum KnowledgeReleaseStatus { CANDIDATE = 'candidate', VALIDATING = 'validating', READY = 'ready', ACTIVE = 'active', SUPERSEDED = 'superseded', FAILED = 'failed', ROLLED_BACK = 'rolled_back' }
export enum KnowledgeDocumentVersionStatus { CANDIDATE = 'candidate', PUBLISHED = 'published', SUPERSEDED = 'superseded', ARCHIVED = 'archived', FAILED = 'failed' }
export enum KnowledgeEmbeddingMetric { COSINE = 'cosine', L2 = 'l2', INNER_PRODUCT = 'inner_product' }
export enum KnowledgeEmbeddingSpaceStatus { ACTIVE = 'active', INACTIVE = 'inactive', INVALID = 'invalid' }
export enum KnowledgeErrorCode { MANIFEST_INVALID = 'manifest_invalid', PATH_NOT_ALLOWED = 'path_not_allowed', LOCALE_PAIR_MISSING = 'locale_pair_missing', CHECKSUM_MISMATCH = 'checksum_mismatch', FRONTMATTER_INVALID = 'frontmatter_invalid', EMBEDDING_UNAVAILABLE = 'embedding_unavailable', EMBEDDING_DIMENSION_MISMATCH = 'embedding_dimension_mismatch', RELEASE_INCOMPLETE = 'release_incomplete', RELEASE_NOT_FOUND = 'release_not_found', INGESTION_FAILED = 'ingestion_failed' }
