export enum AssistantConversationMode { AI = 'ai', WAITING_FOR_SUPPORT = 'waiting_for_support', HUMAN = 'human' }
export enum AssistantConversationStatus { OPEN = 'open', RESOLVED = 'resolved', ARCHIVED = 'archived', DELETED = 'deleted' }
export enum AssistantMessageAuthorType { CUSTOMER = 'customer', ASSISTANT = 'assistant', SUPPORT_AGENT = 'support_agent', SYSTEM = 'system' }
export enum AssistantMessageType { TEXT = 'text', HANDOFF_REQUEST = 'handoff_request', HANDOFF_ACCEPTED = 'handoff_accepted', HANDOFF_RESOLVED = 'handoff_resolved', RETURNED_TO_AI = 'returned_to_ai', SYSTEM_NOTICE = 'system_notice' }
export enum AssistantMessageStatus { PENDING = 'pending', STREAMING = 'streaming', COMPLETED = 'completed', INCOMPLETE = 'incomplete', FAILED = 'failed' }
export enum AssistantGenerationStatus { RESERVED = 'reserved', RUNNING = 'running', COMPLETED = 'completed', INCOMPLETE = 'incomplete', FAILED = 'failed', RATE_LIMITED = 'rate_limited', CANCELLED = 'cancelled' }
export enum AssistantHandoffReason { USER_REQUESTED = 'user_requested', AI_LOW_CONFIDENCE = 'ai_low_confidence', AI_UNAVAILABLE = 'ai_unavailable', ISSUE_UNRESOLVED = 'issue_unresolved' }
export enum AssistantArchiveRestoreState { OPEN_AI = 'open_ai', RESOLVED_AI = 'resolved_ai', ARCHIVED_AI = 'archived_ai', DELETED_AI = 'deleted_ai' }
export enum AssistantCursorScope { ASSISTANT_EVENTS = 'assistant_events' }
export enum AssistantEventRecipientKind { USER = 'user', TOPIC = 'topic' }
export enum AssistantEventTopic { SUPPORT_QUEUE = 'support_queue' }
export enum AssistantDurableEventType { CONVERSATION_CREATED = 'conversation_created', CONVERSATION_UPDATED = 'conversation_updated', CONVERSATION_DELETED = 'conversation_deleted', CONVERSATION_RESTORED = 'conversation_restored', MESSAGE_CREATED = 'message_created', MESSAGE_COMPLETED = 'message_completed', MESSAGE_INCOMPLETE = 'message_incomplete', ASSIGNMENT_UPDATED = 'assignment_updated', SUPPORT_QUEUE_UPDATED = 'support_queue_updated', READ_UPDATED = 'read_updated', AVAILABILITY_UPDATED = 'availability_updated' }
export enum AssistantEphemeralEventType { MESSAGE_SNAPSHOT = 'message_snapshot', TYPING_UPDATED = 'typing_updated', SUPPORT_PRESENCE_UPDATED = 'support_presence_updated' }
export enum AssistantStreamEventType { STREAM_STARTED = 'stream_started', USER_MESSAGE_ACCEPTED = 'user_message_accepted', ASSISTANT_MESSAGE_STARTED = 'assistant_message_started', ASSISTANT_MESSAGE_SNAPSHOT = 'assistant_message_snapshot', CITATIONS_READY = 'citations_ready', ASSISTANT_MESSAGE_COMPLETED = 'assistant_message_completed', ASSISTANT_MESSAGE_INCOMPLETE = 'assistant_message_incomplete', RATE_LIMITED = 'rate_limited', HANDOFF_OFFERED = 'handoff_offered', ERROR = 'error', STREAM_COMPLETED = 'stream_completed' }
export enum AssistantInboxEventType { DURABLE_EVENT = 'durable_event', EPHEMERAL_EVENT = 'ephemeral_event', RESYNC_REQUIRED = 'resync_required', AUTH_EXPIRED = 'auth_expired' }
export enum AssistantResyncReason { CURSOR_EXPIRED = 'cursor_expired', CURSOR_INVALID = 'cursor_invalid', RETENTION_GAP = 'retention_gap' }
export enum AssistantWidgetView { COLLAPSED = 'collapsed', CONVERSATIONS = 'conversations', THREAD = 'thread' }
export enum AssistantConnectionStatus { DISCONNECTED = 'disconnected', CONNECTING = 'connecting', CONNECTED = 'connected', RECONNECTING = 'reconnecting', OFFLINE = 'offline', AUTH_EXPIRED = 'auth_expired' }
export enum AssistantLocalSendStatus { QUEUED = 'queued', SENDING = 'sending', ACCEPTED = 'accepted', FAILED = 'failed' }
export enum AssistantAvailabilityStatus { AVAILABLE = 'available', DEGRADED = 'degraded', DISABLED = 'disabled' }
export enum AssistantGroundingConfidence { HIGH = 'high', MEDIUM = 'medium', LOW = 'low', NONE = 'none' }
export enum AssistantToolName { ACCOUNT_OVERVIEW = 'account_overview', DASHBOARD_SUMMARY = 'dashboard_summary', LISTINGS_SUMMARY = 'listings_summary', LISTING_DETAIL = 'listing_detail', ORDERS_SUMMARY = 'orders_summary', ORDER_DETAIL = 'order_detail', STORE_SETTINGS_SUMMARY = 'store_settings_summary' }
export enum AssistantContextSourceType { KNOWLEDGE_DOCUMENT = 'knowledge_document', ACCOUNT_OVERVIEW = 'account_overview', LISTING = 'listing', ORDER = 'order', DASHBOARD = 'dashboard', SETTINGS = 'settings' }
export enum AssistantLimitReason { USER_REQUEST_RATE = 'user_request_rate', USER_CONCURRENCY = 'user_concurrency', USER_DAILY_TOKENS = 'user_daily_tokens', GLOBAL_CONCURRENCY = 'global_concurrency', GLOBAL_TOKEN_CAPACITY = 'global_token_capacity', LIMITER_UNAVAILABLE = 'limiter_unavailable' }
export enum AssistantLimiterReadiness { NOT_READY = 'not_ready', REBUILDING = 'rebuilding', READY = 'ready', FAILED = 'failed' }
export enum AssistantReservationStatus { PENDING = 'pending', RESERVED = 'reserved', RECONCILED = 'reconciled', RELEASED = 'released', EXPIRED = 'expired', FAILED = 'failed' }
export enum AssistantLeaseStatus { ACTIVE = 'active', RELEASED = 'released', EXPIRED = 'expired' }
export enum AssistantReconcileStatus { PENDING = 'pending', COMPLETED = 'completed', FAILED = 'failed' }
export enum AssistantUsageStatus { SUCCESS = 'success', INCOMPLETE = 'incomplete', FAILED = 'failed', CANCELLED = 'cancelled', RATE_LIMITED = 'rate_limited' }
export enum AssistantErrorCode { CONVERSATION_NOT_FOUND = 'conversation_not_found', CONVERSATION_NOT_OPEN = 'conversation_not_open', CONVERSATION_AI_DISABLED = 'conversation_ai_disabled', CONVERSATION_SUPPORT_ACTIVE = 'conversation_support_active', GENERATION_ALREADY_ACTIVE = 'generation_already_active', MESSAGE_TOO_LONG = 'message_too_long', MESSAGE_NOT_RETRYABLE = 'message_not_retryable', USER_RATE_LIMITED = 'user_rate_limited', TENANT_RATE_LIMITED = 'tenant_rate_limited', GLOBAL_CAPACITY_EXCEEDED = 'global_capacity_exceeded', DAILY_TOKEN_QUOTA_EXCEEDED = 'daily_token_quota_exceeded', ASSISTANT_UNAVAILABLE = 'assistant_unavailable', LIMITER_UNAVAILABLE = 'limiter_unavailable', PROVIDER_UNAVAILABLE = 'provider_unavailable', PROVIDER_TIMEOUT = 'provider_timeout', RETRIEVAL_UNAVAILABLE = 'retrieval_unavailable', SUPPORT_ALREADY_REQUESTED = 'support_already_requested', SUPPORT_ALREADY_CLAIMED = 'support_already_claimed', SUPPORT_NOT_ASSIGNED = 'support_not_assigned', EVENT_CURSOR_INVALID = 'event_cursor_invalid', EVENT_CURSOR_EXPIRED = 'event_cursor_expired', RESYNC_REQUIRED = 'resync_required', AUTH_EXPIRED = 'auth_expired', VALIDATION_FAILED = 'validation_failed', INTERNAL_ERROR = 'internal_error' }
